language: node_js
node_js:
  - 12
os: linux
dist: bionic
# services:
#   - docker
install: true

env:
  - NODE_ENV=production DOCKER_CLI_EXPERIMENTAL=enabled

stages:
  - name: test
    if: branch != multiarch2
  - name: deploy
    if: branch = master && type != pull_request
  - name: deploy-canary
    if: branch = develop && type != pull_request
  - name: multiarch
    if: branch = multiarch2 && type != pull_request
  
before_install:
  - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  
jobs:
  include:
    - stage: test
      script:
        - yarn
        - yarn ci-test
    - stage: deploy
      script:
        - export TARGET_ARCHS=linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make install
        - make prepare
        - make maintenance
        - make frontend
        - make backend
        - docker push antoinejaussoin/retro-board-backend:latest
        - docker push antoinejaussoin/retro-board-frontend:latest
        - docker push antoinejaussoin/retro-board-maintenance:latest
    - stage: deploy-canary
      script:
        - export TARGET_ARCHS=linux/amd64,linux/arm/v7
        - export PACKAGE_VERSION=canary
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make install
        - make prepare
        - make maintenance
        - make frontend
        - make backend
    - stage: multiarch
      script:
        - export TARGET_ARCHS=linux/amd64,linux/arm/v7
        - export PACKAGE_VERSION=multi
        - make install
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker buildx build --platform ${TARGET_ARCHS} -f ./retro-board-maintenance/Dockerfile -t antoinejaussoin/retro-board-maintenance:${PACKAGE_VERSION} --push ./retro-board-maintenance
        - docker buildx build --platform ${TARGET_ARCHS} -f ./retro-board-app/Dockerfile -t antoinejaussoin/retro-board-frontend:${PACKAGE_VERSION} --push .
        - docker buildx build --platform ${TARGET_ARCHS} -f ./retro-board-server/Dockerfile -t antoinejaussoin/retro-board-backend:${PACKAGE_VERSION} --push .
