language: node_js
node_js:
  - 12
os: linux
dist: bionic
services:
  - docker
install: true

env:
  - NODE_ENV=production DOCKER_CLI_EXPERIMENTAL=enabled

stages:
  - name: test
    if: branch != multiarch
  - name: deploy
    if: branch = master && type != pull_request
  - name: deploy-canary
    if: branch = develop && type != pull_request
  - name: deploy-multi
    if: branch = multiarch && type != pull_request

before_install:
  - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

jobs:
  include:
    - stage: test
      script:
        - yarn
        - yarn ci-test
    - stage: deploy
      script:
        - export TARGET_ARCHS=linux/amd64,linux/386,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make prepare
        - make maintenance
        - make frontend
        - make backend
        - docker push antoinejaussoin/retro-board-backend:latest
        - docker push antoinejaussoin/retro-board-frontend:latest
        - docker push antoinejaussoin/retro-board-maintenance:latest
    - stage: deploy-canary
      script:
        - export TARGET_ARCHS=linux/amd64,linux/arm/v7
        - export PACKAGE_VERSION=canary
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make prepare
        - make maintenance
        - make frontend
        - make backend
    - stage: deploy-multi
      script:
        - export TARGET_ARCHS=linux/amd64,linux/386,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6
        - export PACKAGE_VERSION=multi
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make prepare
        - make maintenance
        - make frontend
        - make backend
