language: node_js
node_js:
  - 12
os: linux
dist: bionic
services:
  - docker
install: true

env:
  - NODE_ENV=production DOCKER_CLI_EXPERIMENTAL=enabled

stages:
  - name: test
    if: branch != feature/multi-arch
  - name: deploy
    if: branch = master && type != pull_request
  - name: deploy-canary
    if: branch = develop && type != pull_request
  - name: deploy-multiarch
    if: branch = feature/multi-arch && type != pull_request

before_install:
  - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - lsb_release -cs
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

jobs:
  include:
    - stage: test
      script:
        - yarn
        - yarn ci-test
    - state: deploy-multiarch
      script:
        - export PACKAGE_VERSION=mumu
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make prepare
        - make frontend
        - make backend
    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -f ./retro-board-server/Dockerfile -t antoinejaussoin/retro-board-backend:${PACKAGE_VERSION} -t antoinejaussoin/retro-board-backend:latest .
        - docker build -f ./retro-board-app/Dockerfile -t antoinejaussoin/retro-board-frontend:${PACKAGE_VERSION} -t antoinejaussoin/retro-board-frontend:latest .
        - docker build -f ./retro-board-maintenance/Dockerfile -t antoinejaussoin/retro-board-maintenance:${PACKAGE_VERSION} -t antoinejaussoin/retro-board-maintenance:latest ./retro-board-maintenance
        - docker push antoinejaussoin/retro-board-backend:${PACKAGE_VERSION}
        - docker push antoinejaussoin/retro-board-backend:latest
        - docker push antoinejaussoin/retro-board-frontend:${PACKAGE_VERSION}
        - docker push antoinejaussoin/retro-board-frontend:latest
        - docker push antoinejaussoin/retro-board-maintenance:${PACKAGE_VERSION}
        - docker push antoinejaussoin/retro-board-maintenance:latest
    - stage: deploy-canary
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -f ./retro-board-server/Dockerfile -t antoinejaussoin/retro-board-backend:canary .
        - docker build -f ./retro-board-app/Dockerfile -t antoinejaussoin/retro-board-frontend:canary .
        - docker build -f ./retro-board-maintenance/Dockerfile -t antoinejaussoin/retro-board-maintenance:canary ./retro-board-maintenance
        - docker push antoinejaussoin/retro-board-backend:canary
        - docker push antoinejaussoin/retro-board-frontend:canary
        - docker push antoinejaussoin/retro-board-maintenance:canary
