FROM nginx:alpine

ENV BACKEND_HOST=backend
ENV BACKEND_PORT=3201

COPY --from=antoinejaussoin/retro-board-frontend:m1 /home/node/app/retro-board-app/build /usr/share/nginx/html
COPY ./retro-board-app/docker/nginx.conf.template /etc/nginx/conf.d/default.conf.template
COPY ./retro-board-app/docker/frontend-entrypoint.sh /

RUN ["chmod", "+x", "/frontend-entrypoint.sh"]
ENTRYPOINT ["/frontend-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]