services:
  cypress:
    image: "cypress/included:12.6.0"
    ipc: host
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend
      - CYPRESS_backend_delay=60000
    working_dir: /e2e
    volumes:
      - ./:/e2e

  postgres:
    image: postgres:16
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: some-password
      POSTGRES_USER: postgres
      POSTGRES_DB: retroboard
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  backend:
    image: retro-backend:local
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3201/healthz"]
      interval: 2s
      timeout: 5s
      retries: 30
    environment:
      SELF_HOSTED_ADMIN: 'your@email.com'
      DB_PASSWORD: some-password
      SESSION_SECRET: im-a-secret

    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  frontend:
    image: retro-frontend:local
    depends_on:
      backend:
        condition: service_healthy
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 3201
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  redis:
    image: redis:latest
    depends_on:
      - postgres
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

