name: "Tests & Linting"

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: []

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn ci-test
      - run: yarn ci-lint
      - run: yarn build
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn ci-test
      - run: yarn ci-lint
      - run: yarn build
  test-marketing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./marketing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn ci-lint
      - run: yarn build
  test-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn typecheck
      - run: yarn build
