name: "Tests & Linting"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: []

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm install @biomejs/cli-linux-x64@1.9.4 --no-save
      - run: npm run ci-test
      - run: npm run ci-lint
      - run: npm run build
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm install @biomejs/cli-linux-x64@1.9.4 --no-save
      - run: npm run ci-test
      - run: npm run ci-lint
      - run: npm run build
  test-marketing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./marketing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm install @biomejs/cli-linux-x64@1.9.4 --no-save
      - run: npm run ci-lint
      - run: npm run build
  test-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
