name: "Integration only (test)"

on:
  push:
    branches: [v552/integrationx]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Integration Tests
        run: docker compose -f ./integration/docker-compose.ci.alpha.yml up --exit-code-from cypress
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test videos
          path: integration/cypress/videos/
          retention-days: 14
