name: 'Integration Tests'

on:
  push:
    branches: [v4120/integrationxxxx]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Cypress
        run: docker-compose -f ./integration/docker-compose.ci.yml up --exit-code-from cypress
      