name: "Marketing Build"

on:
  push:
    branches: [v520/self-hosting]

jobs:
  marketing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read VERSION
        id: package
        uses: martinbeentjes/npm-get-version-action@master
      - name: Echo VERSION
        run: echo ${{ steps.package.outputs.current-version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NEW_USERNAME }}
          password: ${{ secrets.DOCKER_NEW_PASSWORD }}
      - name: Build and push Marketing
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: marketing/Dockerfile
          context: marketing
          tags: retrospected/marketing:alpha
          platforms: linux/amd64
          push: true
